repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.1
  hooks:
    # Run the linter.
    - id: ruff-format
      args: [--config=ruff.toml]
    # Run the formatter.
    - id: ruff
      args: [--fix, --config=ruff.toml]